/* matrix.c generated by valac 0.18.1, the Vala compiler
 * generated from matrix.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>


#define LDRAW_MATHS_TYPE_MATRIX (ldraw_maths_matrix_get_type ())
typedef struct _LdrawMathsMatrix LdrawMathsMatrix;

#define LDRAW_MATHS_TYPE_VECTOR (ldraw_maths_vector_get_type ())
typedef struct _LdrawMathsVector LdrawMathsVector;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _ldraw_maths_matrix_free0(var) ((var == NULL) ? NULL : (var = (ldraw_maths_matrix_free (var), NULL)))

typedef float v4sf __attribute__ ((vector_size(16), aligned(16)));

struct _LdrawMathsMatrix {
	v4sf row0;
	v4sf row1;
	v4sf row2;
} __attribute__((aligned(16)));

struct _LdrawMathsVector {
	v4sf values;
} __attribute__((aligned(16)));



extern LdrawMathsMatrix* ldraw_maths_matrix_s_NullMatrix;
LdrawMathsMatrix* ldraw_maths_matrix_s_NullMatrix = NULL;
extern LdrawMathsMatrix* ldraw_maths_matrix_s_Identity;
LdrawMathsMatrix* ldraw_maths_matrix_s_Identity = NULL;

GType ldraw_maths_matrix_get_type (void) G_GNUC_CONST;
LdrawMathsMatrix* ldraw_maths_matrix_dup (const LdrawMathsMatrix* self);
void ldraw_maths_matrix_free (LdrawMathsMatrix* self);
void ldraw_maths_matrix_copy (const LdrawMathsMatrix* self, LdrawMathsMatrix* dest);
void ldraw_maths_matrix_destroy (LdrawMathsMatrix* self);
void ldraw_maths_matrix_init (LdrawMathsMatrix *self, gfloat a, gfloat b, gfloat c, gfloat d, gfloat e, gfloat f, gfloat g, gfloat h, gfloat i);
GType ldraw_maths_vector_get_type (void) G_GNUC_CONST;
LdrawMathsVector* ldraw_maths_vector_dup (const LdrawMathsVector* self);
void ldraw_maths_vector_free (LdrawMathsVector* self);
void ldraw_maths_matrix_init_ForRotation (LdrawMathsMatrix *self, LdrawMathsVector* axis, gfloat angle);
gfloat ldraw_maths_vector_get_Magnitude (LdrawMathsVector* self);
void ldraw_maths_matrix_get_NullMatrix (LdrawMathsMatrix* result);
static gfloat* _vala_array_dup1 (gfloat* self, int length);
void ldraw_maths_vector_Normalized (LdrawMathsVector *self, LdrawMathsVector* result);
gfloat ldraw_maths_vector_get_X (LdrawMathsVector* self);
gfloat ldraw_maths_vector_get_Y (LdrawMathsVector* self);
gfloat ldraw_maths_vector_get_Z (LdrawMathsVector* self);
void ldraw_maths_matrix_TransformMatrix (LdrawMathsMatrix *self, LdrawMathsMatrix* m, LdrawMathsMatrix* result);
void ldraw_maths_matrix_Add (LdrawMathsMatrix *self, LdrawMathsMatrix* m, LdrawMathsMatrix* result);
void ldraw_maths_matrix_Scale (LdrawMathsMatrix *self, gfloat scale, LdrawMathsMatrix* result);
void ldraw_maths_matrix_TransformVector (LdrawMathsMatrix *self, LdrawMathsVector* v, LdrawMathsVector* result);
void ldraw_maths_vector_init (LdrawMathsVector *self, gfloat x, gfloat y, gfloat z);
gfloat ldraw_maths_matrix_get (LdrawMathsMatrix *self, gint row, gint col);
gchar* ldraw_maths_matrix_to_string (LdrawMathsMatrix *self);
void ldraw_maths_matrix_get_Identity (LdrawMathsMatrix* result);
gfloat ldraw_maths_matrix_get_Determinant (LdrawMathsMatrix* self);
static gfloat* _vala_array_dup2 (gfloat* self, int length);


void ldraw_maths_matrix_init (LdrawMathsMatrix *self,
									gfloat a, gfloat b, gfloat c,
									gfloat d, gfloat e, gfloat f,
									gfloat g, gfloat h, gfloat i
							 ) {

	memset (self, 0, sizeof (LdrawMathsMatrix));
	v4sf row0 = {a, b, c, 0.0F};
	v4sf row1 = {d, e, f, 0.0F};
	v4sf row2 = {g, h, i, 0.0F};
	self->row0 = row0;
	self->row1 = row1;
	self->row2 = row2;
}


void ldraw_maths_matrix_init_ForRotation (LdrawMathsMatrix *self, LdrawMathsVector* axis, gfloat angle) {
	LdrawMathsVector _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	LdrawMathsVector _tmp7_ = {0};
	gfloat _tmp8_;
	gfloat _tmp9_;
	gfloat _tmp10_ = 0.0F;
	LdrawMathsVector _tmp11_;
	gfloat _tmp12_;
	gfloat _tmp13_;
	LdrawMathsVector _tmp14_;
	gfloat _tmp15_;
	gfloat _tmp16_;
	gfloat _tmp17_;
	gfloat _tmp18_ = 0.0F;
	LdrawMathsVector _tmp19_;
	gfloat _tmp20_;
	gfloat _tmp21_;
	LdrawMathsVector _tmp22_;
	gfloat _tmp23_;
	gfloat _tmp24_;
	gfloat _tmp25_;
	gfloat _tmp26_ = 0.0F;
	LdrawMathsVector _tmp27_;
	gfloat _tmp28_;
	gfloat _tmp29_;
	gfloat _tmp30_;
	gfloat _tmp31_ = 0.0F;
	LdrawMathsVector _tmp32_;
	gfloat _tmp33_;
	gfloat _tmp34_;
	LdrawMathsVector _tmp35_;
	gfloat _tmp36_;
	gfloat _tmp37_;
	gfloat _tmp38_;
	gfloat _tmp39_ = 0.0F;
	LdrawMathsVector _tmp40_;
	gfloat _tmp41_;
	gfloat _tmp42_;
	gfloat _tmp43_;
	gfloat _tmp44_ = 0.0F;
	LdrawMathsVector _tmp45_;
	gfloat _tmp46_;
	gfloat _tmp47_;
	LdrawMathsVector _tmp48_;
	gfloat _tmp49_;
	gfloat _tmp50_;
	gfloat _tmp51_;
	gfloat _tmp52_ = 0.0F;
	LdrawMathsVector _tmp53_;
	gfloat _tmp54_;
	gfloat _tmp55_;
	gfloat _tmp56_;
	gfloat _tmp57_ = 0.0F;
	gfloat _tmp58_;
	gfloat _tmp59_ = 0.0F;
	LdrawMathsVector _tmp60_;
	gfloat _tmp61_;
	gfloat _tmp62_;
	LdrawMathsVector _tmp63_;
	gfloat _tmp64_;
	gfloat _tmp65_;
	gfloat _tmp66_;
	gfloat _tmp67_ = 0.0F;
	LdrawMathsVector _tmp68_;
	gfloat _tmp69_;
	gfloat _tmp70_;
	LdrawMathsVector _tmp71_;
	gfloat _tmp72_;
	gfloat _tmp73_;
	gfloat _tmp74_;
	gfloat _tmp75_ = 0.0F;
	LdrawMathsVector _tmp76_;
	gfloat _tmp77_;
	gfloat _tmp78_;
	gfloat _tmp79_;
	gfloat _tmp80_ = 0.0F;
	LdrawMathsVector _tmp81_;
	gfloat _tmp82_;
	gfloat _tmp83_;
	LdrawMathsVector _tmp84_;
	gfloat _tmp85_;
	gfloat _tmp86_;
	gfloat _tmp87_;
	gfloat _tmp88_ = 0.0F;
	LdrawMathsVector _tmp89_;
	gfloat _tmp90_;
	gfloat _tmp91_;
	gfloat _tmp92_;
	gfloat _tmp93_ = 0.0F;
	LdrawMathsVector _tmp94_;
	gfloat _tmp95_;
	gfloat _tmp96_;
	LdrawMathsVector _tmp97_;
	gfloat _tmp98_;
	gfloat _tmp99_;
	gfloat _tmp100_;
	gfloat _tmp101_ = 0.0F;
	LdrawMathsVector _tmp102_;
	gfloat _tmp103_;
	gfloat _tmp104_;
	gfloat _tmp105_;
	gfloat _tmp106_ = 0.0F;
	gfloat _tmp107_;
	gfloat _tmp108_ = 0.0F;
	LdrawMathsVector _tmp109_;
	gfloat _tmp110_;
	gfloat _tmp111_;
	LdrawMathsVector _tmp112_;
	gfloat _tmp113_;
	gfloat _tmp114_;
	gfloat _tmp115_;
	gfloat _tmp116_ = 0.0F;
	g_return_if_fail (axis != NULL);
	memset (self, 0, sizeof (LdrawMathsMatrix));
	_tmp0_ = *axis;
	_tmp1_ = ldraw_maths_vector_get_Magnitude (&_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ == ((gfloat) 0)) {
		LdrawMathsMatrix _tmp3_;
		ldraw_maths_matrix_get_NullMatrix (&_tmp3_);

		self->row0 = _tmp3_.row0;
		self->row1 = _tmp3_.row1;
		self->row2 = _tmp3_.row2;

		return self;
	}
	ldraw_maths_vector_Normalized (axis, &_tmp7_);
	*axis = _tmp7_;
	_tmp8_ = angle;
	angle = (gfloat) (_tmp8_ * ((2 * G_PI) / 360));
	_tmp9_ = angle;
	_tmp10_ = cosf (_tmp9_);
	_tmp11_ = *axis;
	_tmp12_ = ldraw_maths_vector_get_X (&_tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = *axis;
	_tmp15_ = ldraw_maths_vector_get_X (&_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = angle;
	_tmp18_ = cosf (_tmp17_);
	_tmp19_ = *axis;
	_tmp20_ = ldraw_maths_vector_get_X (&_tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = *axis;
	_tmp23_ = ldraw_maths_vector_get_Y (&_tmp22_);
	_tmp24_ = _tmp23_;
	_tmp25_ = angle;
	_tmp26_ = cosf (_tmp25_);
	_tmp27_ = *axis;
	_tmp28_ = ldraw_maths_vector_get_Z (&_tmp27_);
	_tmp29_ = _tmp28_;
	_tmp30_ = angle;
	_tmp31_ = sinf (_tmp30_);
	_tmp32_ = *axis;
	_tmp33_ = ldraw_maths_vector_get_X (&_tmp32_);
	_tmp34_ = _tmp33_;
	_tmp35_ = *axis;
	_tmp36_ = ldraw_maths_vector_get_Z (&_tmp35_);
	_tmp37_ = _tmp36_;
	_tmp38_ = angle;
	_tmp39_ = cosf (_tmp38_);
	_tmp40_ = *axis;
	_tmp41_ = ldraw_maths_vector_get_Y (&_tmp40_);
	_tmp42_ = _tmp41_;
	_tmp43_ = angle;
	_tmp44_ = sinf (_tmp43_);
	_tmp45_ = *axis;
	_tmp46_ = ldraw_maths_vector_get_X (&_tmp45_);
	_tmp47_ = _tmp46_;
	_tmp48_ = *axis;
	_tmp49_ = ldraw_maths_vector_get_Y (&_tmp48_);
	_tmp50_ = _tmp49_;
	_tmp51_ = angle;
	_tmp52_ = cosf (_tmp51_);
	_tmp53_ = *axis;
	_tmp54_ = ldraw_maths_vector_get_Z (&_tmp53_);
	_tmp55_ = _tmp54_;
	_tmp56_ = angle;
	_tmp57_ = sinf (_tmp56_);
	_tmp58_ = angle;
	_tmp59_ = cosf (_tmp58_);
	_tmp60_ = *axis;
	_tmp61_ = ldraw_maths_vector_get_Y (&_tmp60_);
	_tmp62_ = _tmp61_;
	_tmp63_ = *axis;
	_tmp64_ = ldraw_maths_vector_get_Y (&_tmp63_);
	_tmp65_ = _tmp64_;
	_tmp66_ = angle;
	_tmp67_ = cosf (_tmp66_);
	_tmp68_ = *axis;
	_tmp69_ = ldraw_maths_vector_get_Y (&_tmp68_);
	_tmp70_ = _tmp69_;
	_tmp71_ = *axis;
	_tmp72_ = ldraw_maths_vector_get_Z (&_tmp71_);
	_tmp73_ = _tmp72_;
	_tmp74_ = angle;
	_tmp75_ = cosf (_tmp74_);
	_tmp76_ = *axis;
	_tmp77_ = ldraw_maths_vector_get_X (&_tmp76_);
	_tmp78_ = _tmp77_;
	_tmp79_ = angle;
	_tmp80_ = sinf (_tmp79_);
	_tmp81_ = *axis;
	_tmp82_ = ldraw_maths_vector_get_X (&_tmp81_);
	_tmp83_ = _tmp82_;
	_tmp84_ = *axis;
	_tmp85_ = ldraw_maths_vector_get_Z (&_tmp84_);
	_tmp86_ = _tmp85_;
	_tmp87_ = angle;
	_tmp88_ = cosf (_tmp87_);
	_tmp89_ = *axis;
	_tmp90_ = ldraw_maths_vector_get_Y (&_tmp89_);
	_tmp91_ = _tmp90_;
	_tmp92_ = angle;
	_tmp93_ = sinf (_tmp92_);
	_tmp94_ = *axis;
	_tmp95_ = ldraw_maths_vector_get_Y (&_tmp94_);
	_tmp96_ = _tmp95_;
	_tmp97_ = *axis;
	_tmp98_ = ldraw_maths_vector_get_Z (&_tmp97_);
	_tmp99_ = _tmp98_;
	_tmp100_ = angle;
	_tmp101_ = cosf (_tmp100_);
	_tmp102_ = *axis;
	_tmp103_ = ldraw_maths_vector_get_X (&_tmp102_);
	_tmp104_ = _tmp103_;
	_tmp105_ = angle;
	_tmp106_ = sinf (_tmp105_);
	_tmp107_ = angle;
	_tmp108_ = cosf (_tmp107_);
	_tmp109_ = *axis;
	_tmp110_ = ldraw_maths_vector_get_Z (&_tmp109_);
	_tmp111_ = _tmp110_;
	_tmp112_ = *axis;
	_tmp113_ = ldraw_maths_vector_get_Z (&_tmp112_);
	_tmp114_ = _tmp113_;
	_tmp115_ = angle;
	_tmp116_ = cosf (_tmp115_);

	v4sf row0 = {
					_tmp10_ + ((_tmp13_ * _tmp16_) * (1 - _tmp18_)),
					((_tmp21_ * _tmp24_) * (1 - _tmp26_)) - (_tmp29_ * _tmp31_),
					((_tmp34_ * _tmp37_) * (1 - _tmp39_)) + (_tmp42_ * _tmp44_),
					0
				};

	v4sf row1 = {
					((_tmp47_ * _tmp50_) * (1 - _tmp52_)) + (_tmp55_ * _tmp57_),
					_tmp59_ + ((_tmp62_ * _tmp65_) * (1 - _tmp67_)),
					((_tmp70_ * _tmp73_) * (1 - _tmp75_)) - (_tmp78_ * _tmp80_),
					0
				};

	v4sf row2 = {
					((_tmp83_ * _tmp86_) * (1 - _tmp88_)) - (_tmp91_ * _tmp93_),
					((_tmp96_ * _tmp99_) * (1 - _tmp101_)) + (_tmp104_ * _tmp106_),
					_tmp108_ + ((_tmp111_ * _tmp114_) * (1 - _tmp116_)),
					0
				};

	self->row0 = row0;
	self->row1 = row1;
	self->row2 = row2;
}


void ldraw_maths_matrix_TransformMatrix (LdrawMathsMatrix *self, LdrawMathsMatrix* m, LdrawMathsMatrix* result) {
	g_return_if_fail (m != NULL);

	v4sf abc = self->row0;
	v4sf bca = __builtin_ia32_shufps(abc, abc, 0xc9);
	v4sf cab = __builtin_ia32_shufps(abc, abc, 0xd2);

	v4sf def = self->row1;
	v4sf efd = __builtin_ia32_shufps(def, def, 0xc9);
	v4sf fde = __builtin_ia32_shufps(def, def, 0xd2);

	v4sf ghi = self->row2;
	v4sf hig = __builtin_ia32_shufps(ghi, ghi, 0xc9);
	v4sf igh = __builtin_ia32_shufps(ghi, ghi, 0xd2);

	v4sf aec = {m->row0[0], m->row1[1], m->row2[2], 0.0F};
	v4sf dhc = {m->row1[0], m->row2[1], m->row0[2], 0.0F};
	v4sf gbf = {m->row2[0], m->row0[1], m->row1[2], 0.0F};

	v4sf row0 = __builtin_ia32_addps(__builtin_ia32_addps(
					__builtin_ia32_mulps(abc, aec),
					__builtin_ia32_mulps(bca, dhc)),
					__builtin_ia32_mulps(cab, gbf));

	v4sf row1 = __builtin_ia32_addps(__builtin_ia32_addps(
					__builtin_ia32_mulps(def, aec),
					__builtin_ia32_mulps(efd, dhc)),
					__builtin_ia32_mulps(fde, gbf));


	v4sf row2 = __builtin_ia32_addps(__builtin_ia32_addps(
					__builtin_ia32_mulps(ghi, aec),
					__builtin_ia32_mulps(hig, dhc)),
					__builtin_ia32_mulps(igh, gbf));

	result->row0 = row0;
	result->row1 = row1;
	result->row2 = row2;

	return;
}


void ldraw_maths_matrix_Add (LdrawMathsMatrix *self, LdrawMathsMatrix* m, LdrawMathsMatrix* result) {

	g_return_if_fail (m != NULL);

	v4sf row0 = __builtin_ia32_addps(self->row0, m->row0);
	v4sf row1 = __builtin_ia32_addps(self->row1, m->row1);
	v4sf row2 = __builtin_ia32_addps(self->row2, m->row2);

	result->row0 = row0;
	result->row1 = row1;
	result->row2 = row2;

	return;
}


void ldraw_maths_matrix_Scale (LdrawMathsMatrix *self, gfloat scale, LdrawMathsMatrix* result) {

	v4sf scaling_vector = {scale, scale, scale, scale};
	v4sf row0 = __builtin_ia32_mulps(self->row0, scaling_vector);
	v4sf row1 = __builtin_ia32_mulps(self->row1, scaling_vector);
	v4sf row2 = __builtin_ia32_mulps(self->row2, scaling_vector);

	result->row0 = row0;
	result->row1 = row1;
	result->row2 = row2;

	return;
}


void ldraw_maths_matrix_TransformVector (LdrawMathsMatrix *self, LdrawMathsVector* v, LdrawMathsVector* result) {


	g_return_if_fail (v != NULL);

	v4sf x_components = __builtin_ia32_mulps(self->row0, v->values);
	v4sf y_components = __builtin_ia32_mulps(self->row1, v->values);
	v4sf z_components = __builtin_ia32_mulps(self->row2, v->values);

	v4sf res = {(x_components[0] + x_components[1] + x_components[2]),
				   (y_components[0] + y_components[1] + y_components[2]),
				   (z_components[0] + z_components[1] + z_components[2]),
				   0.0F};
	result->values = res;

	return;
}


gfloat ldraw_maths_matrix_get (LdrawMathsMatrix *self, gint row, gint col) {
	switch(row)
	{
		case 0:
			return self->row0[col];
		case 1:
			return self->row1[col];
		case 2:
			return self->row2[col];
		default:
			return 0.0F;
	}
}


gchar* ldraw_maths_matrix_to_string (LdrawMathsMatrix *self) {
	gchar* result = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_;
	_tmp2_ = g_strdup_printf ("%g", self->row0[0]);
	_tmp3_ = _tmp2_;

	_tmp6_ = g_strdup_printf ("%g", self->row0[1]);
	_tmp7_ = _tmp6_;

	_tmp10_ = g_strdup_printf ("%g", self->row0[2]);
	_tmp11_ = _tmp10_;

	_tmp14_ = g_strdup_printf ("%g", self->row1[0]);
	_tmp15_ = _tmp14_;

	_tmp18_ = g_strdup_printf ("%g", self->row1[1]);
	_tmp19_ = _tmp18_;

	_tmp22_ = g_strdup_printf ("%g", self->row1[2]);
	_tmp23_ = _tmp22_;

	_tmp26_ = g_strdup_printf ("%g", self->row2[0]);
	_tmp27_ = _tmp26_;

	_tmp30_ = g_strdup_printf ("%g", self->row2[1]);
	_tmp31_ = _tmp30_;

	_tmp34_ = g_strdup_printf ("%g", self->row2[2]);
	_tmp35_ = _tmp34_;
	_tmp36_ = g_strconcat ("(", _tmp3_, ",\t", _tmp7_, ",\t", _tmp11_, ")\n(", _tmp15_, ",\t", _tmp19_, ",\t", _tmp23_, ")\n(", _tmp27_, ",\t", _tmp31_, ",\t", _tmp35_, ")", NULL);
	_tmp37_ = _tmp36_;
	_g_free0 (_tmp35_);
	_g_free0 (_tmp31_);
	_g_free0 (_tmp27_);
	_g_free0 (_tmp23_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp11_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp3_);
	result = _tmp37_;
	return result;
}


static gpointer _ldraw_maths_matrix_dup0 (gpointer self) {
	return self ? ldraw_maths_matrix_dup (self) : NULL;
}


void ldraw_maths_matrix_get_NullMatrix (LdrawMathsMatrix* result) {
	LdrawMathsMatrix* _tmp0_;
	LdrawMathsMatrix* _tmp4_;
	_tmp0_ = ldraw_maths_matrix_s_NullMatrix;
	if (_tmp0_ == NULL) {
		LdrawMathsMatrix _tmp1_ = {0};
		LdrawMathsMatrix _tmp2_;
		LdrawMathsMatrix* _tmp3_;
		ldraw_maths_matrix_init (&_tmp1_, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 0);
		_tmp2_ = _tmp1_;
		_tmp3_ = _ldraw_maths_matrix_dup0 (&_tmp2_);
		_ldraw_maths_matrix_free0 (ldraw_maths_matrix_s_NullMatrix);
		ldraw_maths_matrix_s_NullMatrix = _tmp3_;
		ldraw_maths_matrix_destroy (&_tmp2_);
	}
	_tmp4_ = ldraw_maths_matrix_s_NullMatrix;
	*result = *_tmp4_;
	return;
}


void ldraw_maths_matrix_get_Identity (LdrawMathsMatrix* result) {
	LdrawMathsMatrix* _tmp0_;
	LdrawMathsMatrix* _tmp4_;
	_tmp0_ = ldraw_maths_matrix_s_Identity;
	if (_tmp0_ == NULL) {
		LdrawMathsMatrix _tmp1_ = {0};
		LdrawMathsMatrix _tmp2_;
		LdrawMathsMatrix* _tmp3_;
		ldraw_maths_matrix_init (&_tmp1_, (gfloat) 1, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 1, (gfloat) 0, (gfloat) 0, (gfloat) 0, (gfloat) 1);
		_tmp2_ = _tmp1_;
		_tmp3_ = _ldraw_maths_matrix_dup0 (&_tmp2_);
		_ldraw_maths_matrix_free0 (ldraw_maths_matrix_s_Identity);
		ldraw_maths_matrix_s_Identity = _tmp3_;
		ldraw_maths_matrix_destroy (&_tmp2_);
	}
	_tmp4_ = ldraw_maths_matrix_s_Identity;
	*result = *_tmp4_;
	return;
}


gfloat ldraw_maths_matrix_get_Determinant (LdrawMathsMatrix* self) {

	g_return_val_if_fail (self != NULL, 0.0F);

	v4sf cab = __builtin_ia32_shufps(self->row0, self->row0, 0xd2);
	v4sf efd = __builtin_ia32_shufps(self->row1, self->row1, 0xc9);
	v4sf igh = __builtin_ia32_shufps(self->row2, self->row2, 0xd2);

	v4sf pos = __builtin_ia32_mulps(self->row0, __builtin_ia32_mulps(efd, igh));
	v4sf neg = __builtin_ia32_mulps(cab, __builtin_ia32_mulps(efd, self->row2));

	v4sf foo = __builtin_ia32_subps(pos, neg);

	return foo[0] + foo[1] + foo[2];
}

void ldraw_maths_matrix_copy (const LdrawMathsMatrix* self, LdrawMathsMatrix* dest) {
	dest->row0 = self->row0;
	dest->row1 = self->row1;
	dest->row2 = self->row2;
}


void ldraw_maths_matrix_destroy (LdrawMathsMatrix* self) {
}


LdrawMathsMatrix* ldraw_maths_matrix_dup (const LdrawMathsMatrix* self) {
	LdrawMathsMatrix* dup;
	dup = g_new0 (LdrawMathsMatrix, 1);
	ldraw_maths_matrix_copy (self, dup);
	return dup;
}


void ldraw_maths_matrix_free (LdrawMathsMatrix* self) {
	ldraw_maths_matrix_destroy (self);
	g_free (self);
}


GType ldraw_maths_matrix_get_type (void) {
	static volatile gsize ldraw_maths_matrix_type_id__volatile = 0;
	if (g_once_init_enter (&ldraw_maths_matrix_type_id__volatile)) {
		GType ldraw_maths_matrix_type_id;
		ldraw_maths_matrix_type_id = g_boxed_type_register_static ("LdrawMathsMatrix", (GBoxedCopyFunc) ldraw_maths_matrix_dup, (GBoxedFreeFunc) ldraw_maths_matrix_free);
		g_once_init_leave (&ldraw_maths_matrix_type_id__volatile, ldraw_maths_matrix_type_id);
	}
	return ldraw_maths_matrix_type_id__volatile;
}



