/* vector.c generated by valac 0.18.1, the Vala compiler
 * generated from vector.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>


#define LDRAW_MATHS_TYPE_VECTOR (ldraw_maths_vector_get_type ())
typedef struct _LdrawMathsVector LdrawMathsVector;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _ldraw_maths_vector_free0(var) ((var == NULL) ? NULL : (var = (ldraw_maths_vector_free (var), NULL)))

struct _LdrawMathsVector {
	gfloat m_Values[3];
};


extern LdrawMathsVector* ldraw_maths_vector_s_NullVector;
LdrawMathsVector* ldraw_maths_vector_s_NullVector = NULL;

GType ldraw_maths_vector_get_type (void) G_GNUC_CONST;
LdrawMathsVector* ldraw_maths_vector_dup (const LdrawMathsVector* self);
void ldraw_maths_vector_free (LdrawMathsVector* self);
void ldraw_maths_vector_init (LdrawMathsVector *self, gfloat x, gfloat y, gfloat z);
void ldraw_maths_vector_init_Min (LdrawMathsVector *self, LdrawMathsVector* a, LdrawMathsVector* b);
gfloat ldraw_maths_vector_get_X (LdrawMathsVector* self);
gfloat ldraw_maths_vector_get_Y (LdrawMathsVector* self);
gfloat ldraw_maths_vector_get_Z (LdrawMathsVector* self);
void ldraw_maths_vector_init_Max (LdrawMathsVector *self, LdrawMathsVector* a, LdrawMathsVector* b);
void ldraw_maths_vector_Add (LdrawMathsVector *self, LdrawMathsVector* v, LdrawMathsVector* result);
void ldraw_maths_vector_Subtract (LdrawMathsVector *self, LdrawMathsVector* v, LdrawMathsVector* result);
void ldraw_maths_vector_Cross (LdrawMathsVector *self, LdrawMathsVector* v, LdrawMathsVector* result);
gfloat ldraw_maths_vector_Dot (LdrawMathsVector *self, LdrawMathsVector* v);
void ldraw_maths_vector_Normalized (LdrawMathsVector *self, LdrawMathsVector* result);
void ldraw_maths_vector_Scale (LdrawMathsVector *self, gfloat scale, LdrawMathsVector* result);
gfloat ldraw_maths_vector_get_Magnitude (LdrawMathsVector* self);
gchar* ldraw_maths_vector_to_string (LdrawMathsVector *self);
void ldraw_maths_vector_get_NullVector (LdrawMathsVector* result);


void ldraw_maths_vector_init (LdrawMathsVector *self, gfloat x, gfloat y, gfloat z) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_[3] = {0};
	memset (self, 0, sizeof (LdrawMathsVector));
	_tmp0_ = x;
	_tmp1_ = y;
	_tmp2_ = z;
	_tmp3_[0] = _tmp0_;
	_tmp3_[1] = _tmp1_;
	_tmp3_[2] = _tmp2_;
	memcpy ((*self).m_Values, _tmp3_, 3 * sizeof (gfloat));
}


void ldraw_maths_vector_init_Min (LdrawMathsVector *self, LdrawMathsVector* a, LdrawMathsVector* b) {
	LdrawMathsVector _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	LdrawMathsVector _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_ = 0.0F;
	LdrawMathsVector _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	LdrawMathsVector _tmp10_;
	gfloat _tmp11_;
	gfloat _tmp12_;
	gfloat _tmp13_ = 0.0F;
	LdrawMathsVector _tmp14_;
	gfloat _tmp15_;
	gfloat _tmp16_;
	LdrawMathsVector _tmp17_;
	gfloat _tmp18_;
	gfloat _tmp19_;
	gfloat _tmp20_ = 0.0F;
	gfloat _tmp21_[3] = {0};
	g_return_if_fail (a != NULL);
	g_return_if_fail (b != NULL);
	memset (self, 0, sizeof (LdrawMathsVector));
	_tmp0_ = *a;
	_tmp1_ = ldraw_maths_vector_get_X (&_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = *b;
	_tmp4_ = ldraw_maths_vector_get_X (&_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = fminf (_tmp2_, _tmp5_);
	_tmp7_ = *a;
	_tmp8_ = ldraw_maths_vector_get_Y (&_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = *b;
	_tmp11_ = ldraw_maths_vector_get_Y (&_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = fminf (_tmp9_, _tmp12_);
	_tmp14_ = *a;
	_tmp15_ = ldraw_maths_vector_get_Z (&_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = *b;
	_tmp18_ = ldraw_maths_vector_get_Z (&_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = fminf (_tmp16_, _tmp19_);
	_tmp21_[0] = _tmp6_;
	_tmp21_[1] = _tmp13_;
	_tmp21_[2] = _tmp20_;
	memcpy ((*self).m_Values, _tmp21_, 3 * sizeof (gfloat));
}


void ldraw_maths_vector_init_Max (LdrawMathsVector *self, LdrawMathsVector* a, LdrawMathsVector* b) {
	LdrawMathsVector _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	LdrawMathsVector _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_ = 0.0F;
	LdrawMathsVector _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	LdrawMathsVector _tmp10_;
	gfloat _tmp11_;
	gfloat _tmp12_;
	gfloat _tmp13_ = 0.0F;
	LdrawMathsVector _tmp14_;
	gfloat _tmp15_;
	gfloat _tmp16_;
	LdrawMathsVector _tmp17_;
	gfloat _tmp18_;
	gfloat _tmp19_;
	gfloat _tmp20_ = 0.0F;
	gfloat _tmp21_[3] = {0};
	g_return_if_fail (a != NULL);
	g_return_if_fail (b != NULL);
	memset (self, 0, sizeof (LdrawMathsVector));
	_tmp0_ = *a;
	_tmp1_ = ldraw_maths_vector_get_X (&_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = *b;
	_tmp4_ = ldraw_maths_vector_get_X (&_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = fmaxf (_tmp2_, _tmp5_);
	_tmp7_ = *a;
	_tmp8_ = ldraw_maths_vector_get_Y (&_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = *b;
	_tmp11_ = ldraw_maths_vector_get_Y (&_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = fmaxf (_tmp9_, _tmp12_);
	_tmp14_ = *a;
	_tmp15_ = ldraw_maths_vector_get_Z (&_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = *b;
	_tmp18_ = ldraw_maths_vector_get_Z (&_tmp17_);
	_tmp19_ = _tmp18_;
	_tmp20_ = fmaxf (_tmp16_, _tmp19_);
	_tmp21_[0] = _tmp6_;
	_tmp21_[1] = _tmp13_;
	_tmp21_[2] = _tmp20_;
	memcpy ((*self).m_Values, _tmp21_, 3 * sizeof (gfloat));
}


void ldraw_maths_vector_Add (LdrawMathsVector *self, LdrawMathsVector* v, LdrawMathsVector* result) {
	gfloat _tmp0_;
	LdrawMathsVector _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	LdrawMathsVector _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	LdrawMathsVector _tmp7_;
	gfloat _tmp8_;
	LdrawMathsVector _tmp9_ = {0};
	g_return_if_fail (v != NULL);
	_tmp0_ = (*self).m_Values[0];
	_tmp1_ = *v;
	_tmp2_ = _tmp1_.m_Values[0];
	_tmp3_ = (*self).m_Values[1];
	_tmp4_ = *v;
	_tmp5_ = _tmp4_.m_Values[1];
	_tmp6_ = (*self).m_Values[2];
	_tmp7_ = *v;
	_tmp8_ = _tmp7_.m_Values[2];
	ldraw_maths_vector_init (&_tmp9_, _tmp0_ + _tmp2_, _tmp3_ + _tmp5_, _tmp6_ + _tmp8_);
	*result = _tmp9_;
	return;
}


void ldraw_maths_vector_Subtract (LdrawMathsVector *self, LdrawMathsVector* v, LdrawMathsVector* result) {
	gfloat _tmp0_;
	LdrawMathsVector _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	LdrawMathsVector _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	LdrawMathsVector _tmp7_;
	gfloat _tmp8_;
	LdrawMathsVector _tmp9_ = {0};
	g_return_if_fail (v != NULL);
	_tmp0_ = (*self).m_Values[0];
	_tmp1_ = *v;
	_tmp2_ = _tmp1_.m_Values[0];
	_tmp3_ = (*self).m_Values[1];
	_tmp4_ = *v;
	_tmp5_ = _tmp4_.m_Values[1];
	_tmp6_ = (*self).m_Values[2];
	_tmp7_ = *v;
	_tmp8_ = _tmp7_.m_Values[2];
	ldraw_maths_vector_init (&_tmp9_, _tmp0_ - _tmp2_, _tmp3_ - _tmp5_, _tmp6_ - _tmp8_);
	*result = _tmp9_;
	return;
}


void ldraw_maths_vector_Cross (LdrawMathsVector *self, LdrawMathsVector* v, LdrawMathsVector* result) {
	gfloat _tmp0_;
	LdrawMathsVector _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	LdrawMathsVector _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	LdrawMathsVector _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	LdrawMathsVector _tmp10_;
	gfloat _tmp11_;
	gfloat _tmp12_;
	LdrawMathsVector _tmp13_;
	gfloat _tmp14_;
	gfloat _tmp15_;
	LdrawMathsVector _tmp16_;
	gfloat _tmp17_;
	LdrawMathsVector _tmp18_ = {0};
	g_return_if_fail (v != NULL);
	_tmp0_ = (*self).m_Values[1];
	_tmp1_ = *v;
	_tmp2_ = _tmp1_.m_Values[2];
	_tmp3_ = (*self).m_Values[2];
	_tmp4_ = *v;
	_tmp5_ = _tmp4_.m_Values[1];
	_tmp6_ = (*self).m_Values[2];
	_tmp7_ = *v;
	_tmp8_ = _tmp7_.m_Values[0];
	_tmp9_ = (*self).m_Values[0];
	_tmp10_ = *v;
	_tmp11_ = _tmp10_.m_Values[2];
	_tmp12_ = (*self).m_Values[0];
	_tmp13_ = *v;
	_tmp14_ = _tmp13_.m_Values[1];
	_tmp15_ = (*self).m_Values[1];
	_tmp16_ = *v;
	_tmp17_ = _tmp16_.m_Values[0];
	ldraw_maths_vector_init (&_tmp18_, (_tmp0_ * _tmp2_) - (_tmp3_ * _tmp5_), (_tmp6_ * _tmp8_) - (_tmp9_ * _tmp11_), (_tmp12_ * _tmp14_) - (_tmp15_ * _tmp17_));
	*result = _tmp18_;
	return;
}


gfloat ldraw_maths_vector_Dot (LdrawMathsVector *self, LdrawMathsVector* v) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	LdrawMathsVector _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	LdrawMathsVector _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	LdrawMathsVector _tmp7_;
	gfloat _tmp8_;
	g_return_val_if_fail (v != NULL, 0.0F);
	_tmp0_ = (*self).m_Values[0];
	_tmp1_ = *v;
	_tmp2_ = _tmp1_.m_Values[0];
	_tmp3_ = (*self).m_Values[1];
	_tmp4_ = *v;
	_tmp5_ = _tmp4_.m_Values[1];
	_tmp6_ = (*self).m_Values[2];
	_tmp7_ = *v;
	_tmp8_ = _tmp7_.m_Values[2];
	result = ((_tmp0_ * _tmp2_) + (_tmp3_ * _tmp5_)) + (_tmp6_ * _tmp8_);
	return result;
}


void ldraw_maths_vector_Normalized (LdrawMathsVector *self, LdrawMathsVector* result) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	LdrawMathsVector _tmp2_ = {0};
	_tmp0_ = ldraw_maths_vector_get_Magnitude (&(*self));
	_tmp1_ = _tmp0_;
	ldraw_maths_vector_Scale (&(*self), 1.0f / _tmp1_, &_tmp2_);
	*result = _tmp2_;
	return;
}


void ldraw_maths_vector_Scale (LdrawMathsVector *self, gfloat scale, LdrawMathsVector* result) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	LdrawMathsVector _tmp6_ = {0};
	_tmp0_ = (*self).m_Values[0];
	_tmp1_ = scale;
	_tmp2_ = (*self).m_Values[1];
	_tmp3_ = scale;
	_tmp4_ = (*self).m_Values[2];
	_tmp5_ = scale;
	ldraw_maths_vector_init (&_tmp6_, _tmp0_ * _tmp1_, _tmp2_ * _tmp3_, _tmp4_ * _tmp5_);
	*result = _tmp6_;
	return;
}


gchar* ldraw_maths_vector_to_string (LdrawMathsVector *self) {
	gchar* result = NULL;
	gfloat _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	gfloat _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	gfloat _tmp6_;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_;
	_tmp0_ = (*self).m_Values[0];
	_tmp1_ = g_strdup_printf ("%g", _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = (*self).m_Values[1];
	_tmp4_ = g_strdup_printf ("%g", _tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = (*self).m_Values[2];
	_tmp7_ = g_strdup_printf ("%g", _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = g_strconcat ("( ", _tmp2_, ", ", _tmp5_, ", ", _tmp8_, " )", NULL);
	_tmp10_ = _tmp9_;
	_g_free0 (_tmp8_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	result = _tmp10_;
	return result;
}


static gpointer _ldraw_maths_vector_dup0 (gpointer self) {
	return self ? ldraw_maths_vector_dup (self) : NULL;
}


void ldraw_maths_vector_get_NullVector (LdrawMathsVector* result) {
	LdrawMathsVector* _tmp0_;
	LdrawMathsVector* _tmp3_;
	_tmp0_ = ldraw_maths_vector_s_NullVector;
	if (_tmp0_ == NULL) {
		LdrawMathsVector _tmp1_ = {0};
		LdrawMathsVector* _tmp2_;
		ldraw_maths_vector_init (&_tmp1_, (gfloat) 0, (gfloat) 0, (gfloat) 0);
		_tmp2_ = _ldraw_maths_vector_dup0 (&_tmp1_);
		_ldraw_maths_vector_free0 (ldraw_maths_vector_s_NullVector);
		ldraw_maths_vector_s_NullVector = _tmp2_;
	}
	_tmp3_ = ldraw_maths_vector_s_NullVector;
	*result = *_tmp3_;
	return;
}


gfloat ldraw_maths_vector_get_X (LdrawMathsVector* self) {
	gfloat result;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = (*self).m_Values[0];
	result = _tmp0_;
	return result;
}


gfloat ldraw_maths_vector_get_Y (LdrawMathsVector* self) {
	gfloat result;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = (*self).m_Values[1];
	result = _tmp0_;
	return result;
}


gfloat ldraw_maths_vector_get_Z (LdrawMathsVector* self) {
	gfloat result;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = (*self).m_Values[2];
	result = _tmp0_;
	return result;
}


gfloat ldraw_maths_vector_get_Magnitude (LdrawMathsVector* self) {
	gfloat result;
	gfloat _tmp0_ = 0.0F;
	gfloat _tmp1_ = 0.0F;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = ldraw_maths_vector_Dot (&(*self), &(*self));
	_tmp1_ = sqrtf (_tmp0_);
	result = _tmp1_;
	return result;
}


LdrawMathsVector* ldraw_maths_vector_dup (const LdrawMathsVector* self) {
	LdrawMathsVector* dup;
	dup = g_new0 (LdrawMathsVector, 1);
	memcpy (dup, self, sizeof (LdrawMathsVector));
	return dup;
}


void ldraw_maths_vector_free (LdrawMathsVector* self) {
	g_free (self);
}


GType ldraw_maths_vector_get_type (void) {
	static volatile gsize ldraw_maths_vector_type_id__volatile = 0;
	if (g_once_init_enter (&ldraw_maths_vector_type_id__volatile)) {
		GType ldraw_maths_vector_type_id;
		ldraw_maths_vector_type_id = g_boxed_type_register_static ("LdrawMathsVector", (GBoxedCopyFunc) ldraw_maths_vector_dup, (GBoxedFreeFunc) ldraw_maths_vector_free);
		g_once_init_leave (&ldraw_maths_vector_type_id__volatile, ldraw_maths_vector_type_id);
	}
	return ldraw_maths_vector_type_id__volatile;
}



